package plateauapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"

	"github.com/samber/lo"
)

// Prefecture is the resolver for the prefecture field.
func (r *cityResolver) Prefecture(ctx context.Context, obj *City) (*Prefecture, error) {
	return to[*Prefecture](r.Repo.Node(ctx, obj.PrefectureID))
}

// Wards is the resolver for the wards field.
func (r *cityResolver) Wards(ctx context.Context, obj *City) ([]*Ward, error) {
	areas, err := r.Repo.Areas(ctx, &AreasInput{
		ParentCode: lo.ToPtr(obj.Code),
	})
	if err != nil {
		return nil, err
	}

	return lo.FilterMap(areas, func(a Area, _ int) (*Ward, bool) {
		if m, ok := a.(*Ward); ok {
			return m, ok
		}
		return nil, false
	}), nil
}

// Datasets is the resolver for the datasets field.
func (r *cityResolver) Datasets(ctx context.Context, obj *City, input *DatasetsInput) ([]Dataset, error) {
	if input == nil {
		input = &DatasetsInput{}
	}
	input.AreaCodes = []AreaCode{obj.Code}
	return r.Repo.Datasets(ctx, input)
}

// Parent is the resolver for the parent field.
func (r *cityResolver) Parent(ctx context.Context, obj *City) (*Prefecture, error) {
	return r.Prefecture(ctx, obj)
}

// Citygml is the resolver for the citygml field.
func (r *cityResolver) Citygml(ctx context.Context, obj *City) (*CityGMLDataset, error) {
	if obj.CitygmlID == nil {
		return nil, nil
	}
	return to[*CityGMLDataset](r.Repo.Node(ctx, *obj.CitygmlID))
}

// Prefecture is the resolver for the prefecture field.
func (r *cityGMLDatasetResolver) Prefecture(ctx context.Context, obj *CityGMLDataset) (*Prefecture, error) {
	return to[*Prefecture](r.Repo.Node(ctx, obj.PrefectureID))
}

// City is the resolver for the city field.
func (r *cityGMLDatasetResolver) City(ctx context.Context, obj *CityGMLDataset) (*City, error) {
	return to[*City](r.Repo.Node(ctx, obj.CityID))
}

// PlateauSpecMinor is the resolver for the plateauSpecMinor field.
func (r *cityGMLDatasetResolver) PlateauSpecMinor(ctx context.Context, obj *CityGMLDataset) (*PlateauSpecMinor, error) {
	return to[*PlateauSpecMinor](r.Repo.Node(ctx, obj.PlateauSpecMinorID))
}

// Prefecture is the resolver for the prefecture field.
func (r *genericDatasetResolver) Prefecture(ctx context.Context, obj *GenericDataset) (*Prefecture, error) {
	if obj.PrefectureID == nil {
		return nil, nil
	}
	return to[*Prefecture](r.Repo.Node(ctx, *obj.PrefectureID))
}

// City is the resolver for the city field.
func (r *genericDatasetResolver) City(ctx context.Context, obj *GenericDataset) (*City, error) {
	if obj.CityID == nil {
		return nil, nil
	}
	return to[*City](r.Repo.Node(ctx, *obj.CityID))
}

// Ward is the resolver for the ward field.
func (r *genericDatasetResolver) Ward(ctx context.Context, obj *GenericDataset) (*Ward, error) {
	if obj.WardID == nil {
		return nil, nil
	}
	return to[*Ward](r.Repo.Node(ctx, *obj.WardID))
}

// Type is the resolver for the type field.
func (r *genericDatasetResolver) Type(ctx context.Context, obj *GenericDataset) (*GenericDatasetType, error) {
	return to[*GenericDatasetType](r.Repo.Node(ctx, obj.TypeID))
}

// Parent is the resolver for the parent field.
func (r *genericDatasetItemResolver) Parent(ctx context.Context, obj *GenericDatasetItem) (*GenericDataset, error) {
	return to[*GenericDataset](r.Repo.Node(ctx, obj.ParentID))
}

// Datasets is the resolver for the datasets field.
func (r *genericDatasetTypeResolver) Datasets(ctx context.Context, obj *GenericDatasetType, input *DatasetsInput) ([]*GenericDataset, error) {
	if input == nil {
		input = &DatasetsInput{}
	}
	input.IncludeTypes = []string{obj.Code}
	input.ExcludeTypes = nil
	datasets, err := r.Repo.Datasets(ctx, input)
	if err != nil {
		return nil, err
	}

	return lo.FilterMap(datasets, func(d Dataset, _ int) (*GenericDataset, bool) {
		if m, ok := d.(*GenericDataset); ok {
			return m, ok
		}
		return nil, false
	}), nil
}

// Prefecture is the resolver for the prefecture field.
func (r *plateauDatasetResolver) Prefecture(ctx context.Context, obj *PlateauDataset) (*Prefecture, error) {
	if obj.PrefectureID == nil {
		return nil, nil
	}
	return to[*Prefecture](r.Repo.Node(ctx, *obj.PrefectureID))
}

// City is the resolver for the city field.
func (r *plateauDatasetResolver) City(ctx context.Context, obj *PlateauDataset) (*City, error) {
	if obj.CityID == nil {
		return nil, nil
	}
	return to[*City](r.Repo.Node(ctx, *obj.CityID))
}

// Ward is the resolver for the ward field.
func (r *plateauDatasetResolver) Ward(ctx context.Context, obj *PlateauDataset) (*Ward, error) {
	if obj.WardID == nil {
		return nil, nil
	}
	return to[*Ward](r.Repo.Node(ctx, *obj.WardID))
}

// Type is the resolver for the type field.
func (r *plateauDatasetResolver) Type(ctx context.Context, obj *PlateauDataset) (*PlateauDatasetType, error) {
	return to[*PlateauDatasetType](r.Repo.Node(ctx, obj.TypeID))
}

// PlateauSpecMinor is the resolver for the plateauSpecMinor field.
func (r *plateauDatasetResolver) PlateauSpecMinor(ctx context.Context, obj *PlateauDataset) (*PlateauSpecMinor, error) {
	return to[*PlateauSpecMinor](r.Repo.Node(ctx, obj.PlateauSpecMinorID))
}

// Parent is the resolver for the parent field.
func (r *plateauDatasetItemResolver) Parent(ctx context.Context, obj *PlateauDatasetItem) (*PlateauDataset, error) {
	return to[*PlateauDataset](r.Repo.Node(ctx, obj.ParentID))
}

// PlateauSpec is the resolver for the plateauSpec field.
func (r *plateauDatasetTypeResolver) PlateauSpec(ctx context.Context, obj *PlateauDatasetType) (*PlateauSpec, error) {
	return to[*PlateauSpec](r.Repo.Node(ctx, obj.PlateauSpecID))
}

// Datasets is the resolver for the datasets field.
func (r *plateauDatasetTypeResolver) Datasets(ctx context.Context, obj *PlateauDatasetType, input *DatasetsInput) ([]*PlateauDataset, error) {
	if input == nil {
		input = &DatasetsInput{}
	}
	input.IncludeTypes = []string{obj.Code}
	input.ExcludeTypes = nil
	datasets, err := r.Repo.Datasets(ctx, input)
	if err != nil {
		return nil, err
	}

	return lo.FilterMap(datasets, func(d Dataset, _ int) (*PlateauDataset, bool) {
		if m, ok := d.(*PlateauDataset); ok {
			return m, ok
		}
		return nil, false
	}), nil
}

// DatasetTypes is the resolver for the datasetTypes field.
func (r *plateauSpecResolver) DatasetTypes(ctx context.Context, obj *PlateauSpec) ([]*PlateauDatasetType, error) {
	types, err := r.Repo.DatasetTypes(ctx, &DatasetTypesInput{
		PlateauSpec: lo.ToPtr(fmt.Sprintf("%d", obj.MajorVersion)),
	})
	if err != nil {
		return nil, err
	}

	return lo.FilterMap(types, func(d DatasetType, _ int) (*PlateauDatasetType, bool) {
		if m, ok := d.(*PlateauDatasetType); ok {
			return m, ok
		}
		return nil, false
	}), nil
}

// Parent is the resolver for the parent field.
func (r *plateauSpecMinorResolver) Parent(ctx context.Context, obj *PlateauSpecMinor) (*PlateauSpec, error) {
	return to[*PlateauSpec](r.Repo.Node(ctx, obj.ParentID))
}

// Datasets is the resolver for the datasets field.
func (r *plateauSpecMinorResolver) Datasets(ctx context.Context, obj *PlateauSpecMinor, input *DatasetsInput) ([]Dataset, error) {
	if input == nil {
		input = &DatasetsInput{}
	}
	input.PlateauSpec = lo.ToPtr(obj.Version)
	return r.Repo.Datasets(ctx, input)
}

// Cities is the resolver for the cities field.
func (r *prefectureResolver) Cities(ctx context.Context, obj *Prefecture) ([]*City, error) {
	areas, err := r.Repo.Areas(ctx, &AreasInput{
		ParentCode: lo.ToPtr(obj.Code),
	})
	if err != nil {
		return nil, err
	}

	return lo.FilterMap(areas, func(a Area, _ int) (*City, bool) {
		if m, ok := a.(*City); ok {
			return m, ok
		}
		return nil, false
	}), nil
}

// Datasets is the resolver for the datasets field.
func (r *prefectureResolver) Datasets(ctx context.Context, obj *Prefecture, input *DatasetsInput) ([]Dataset, error) {
	if input == nil {
		input = &DatasetsInput{}
	}
	input.AreaCodes = []AreaCode{obj.Code}
	return r.Repo.Datasets(ctx, input)
}

// Parent is the resolver for the parent field.
func (r *prefectureResolver) Parent(ctx context.Context, obj *Prefecture) (Area, error) {
	return nil, nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id ID) (Node, error) {
	return r.Repo.Node(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []ID) ([]Node, error) {
	return r.Repo.Nodes(ctx, ids)
}

// Area is the resolver for the area field.
func (r *queryResolver) Area(ctx context.Context, code AreaCode) (Area, error) {
	return r.Repo.Area(ctx, code)
}

// Areas is the resolver for the areas field.
func (r *queryResolver) Areas(ctx context.Context, input *AreasInput) ([]Area, error) {
	return r.Repo.Areas(ctx, input)
}

// DatasetTypes is the resolver for the datasetTypes field.
func (r *queryResolver) DatasetTypes(ctx context.Context, input *DatasetTypesInput) ([]DatasetType, error) {
	return r.Repo.DatasetTypes(ctx, input)
}

// Datasets is the resolver for the datasets field.
func (r *queryResolver) Datasets(ctx context.Context, input *DatasetsInput) ([]Dataset, error) {
	return r.Repo.Datasets(ctx, input)
}

// PlateauSpecs is the resolver for the plateauSpecs field.
func (r *queryResolver) PlateauSpecs(ctx context.Context) ([]*PlateauSpec, error) {
	return r.Repo.PlateauSpecs(ctx)
}

// Years is the resolver for the years field.
func (r *queryResolver) Years(ctx context.Context) ([]int, error) {
	return r.Repo.Years(ctx)
}

// Prefecture is the resolver for the prefecture field.
func (r *relatedDatasetResolver) Prefecture(ctx context.Context, obj *RelatedDataset) (*Prefecture, error) {
	if obj.PrefectureID == nil {
		return nil, nil
	}
	return to[*Prefecture](r.Repo.Node(ctx, *obj.PrefectureID))
}

// City is the resolver for the city field.
func (r *relatedDatasetResolver) City(ctx context.Context, obj *RelatedDataset) (*City, error) {
	if obj.CityID == nil {
		return nil, nil
	}
	return to[*City](r.Repo.Node(ctx, *obj.CityID))
}

// Ward is the resolver for the ward field.
func (r *relatedDatasetResolver) Ward(ctx context.Context, obj *RelatedDataset) (*Ward, error) {
	if obj.WardID == nil {
		return nil, nil
	}
	return to[*Ward](r.Repo.Node(ctx, *obj.WardID))
}

// Type is the resolver for the type field.
func (r *relatedDatasetResolver) Type(ctx context.Context, obj *RelatedDataset) (*RelatedDatasetType, error) {
	return to[*RelatedDatasetType](r.Repo.Node(ctx, obj.TypeID))
}

// Parent is the resolver for the parent field.
func (r *relatedDatasetItemResolver) Parent(ctx context.Context, obj *RelatedDatasetItem) (*RelatedDataset, error) {
	return to[*RelatedDataset](r.Repo.Node(ctx, obj.ParentID))
}

// Datasets is the resolver for the datasets field.
func (r *relatedDatasetTypeResolver) Datasets(ctx context.Context, obj *RelatedDatasetType, input *DatasetsInput) ([]*RelatedDataset, error) {
	if input == nil {
		input = &DatasetsInput{}
	}
	input.IncludeTypes = []string{obj.Code}
	input.ExcludeTypes = nil
	datasets, err := r.Repo.Datasets(ctx, input)
	if err != nil {
		return nil, err
	}

	return lo.FilterMap(datasets, func(d Dataset, _ int) (*RelatedDataset, bool) {
		if m, ok := d.(*RelatedDataset); ok {
			return m, ok
		}
		return nil, false
	}), nil
}

// Prefecture is the resolver for the prefecture field.
func (r *wardResolver) Prefecture(ctx context.Context, obj *Ward) (*Prefecture, error) {
	return to[*Prefecture](r.Repo.Node(ctx, obj.PrefectureID))
}

// City is the resolver for the city field.
func (r *wardResolver) City(ctx context.Context, obj *Ward) (*City, error) {
	return to[*City](r.Repo.Node(ctx, obj.CityID))
}

// Datasets is the resolver for the datasets field.
func (r *wardResolver) Datasets(ctx context.Context, obj *Ward, input *DatasetsInput) ([]Dataset, error) {
	if input == nil {
		input = &DatasetsInput{}
	}
	input.AreaCodes = []AreaCode{obj.Code}
	return r.Repo.Datasets(ctx, input)
}

// Parent is the resolver for the parent field.
func (r *wardResolver) Parent(ctx context.Context, obj *Ward) (*City, error) {
	return r.City(ctx, obj)
}

// City returns CityResolver implementation.
func (r *Resolver) City() CityResolver { return &cityResolver{r} }

// CityGMLDataset returns CityGMLDatasetResolver implementation.
func (r *Resolver) CityGMLDataset() CityGMLDatasetResolver { return &cityGMLDatasetResolver{r} }

// GenericDataset returns GenericDatasetResolver implementation.
func (r *Resolver) GenericDataset() GenericDatasetResolver { return &genericDatasetResolver{r} }

// GenericDatasetItem returns GenericDatasetItemResolver implementation.
func (r *Resolver) GenericDatasetItem() GenericDatasetItemResolver {
	return &genericDatasetItemResolver{r}
}

// GenericDatasetType returns GenericDatasetTypeResolver implementation.
func (r *Resolver) GenericDatasetType() GenericDatasetTypeResolver {
	return &genericDatasetTypeResolver{r}
}

// PlateauDataset returns PlateauDatasetResolver implementation.
func (r *Resolver) PlateauDataset() PlateauDatasetResolver { return &plateauDatasetResolver{r} }

// PlateauDatasetItem returns PlateauDatasetItemResolver implementation.
func (r *Resolver) PlateauDatasetItem() PlateauDatasetItemResolver {
	return &plateauDatasetItemResolver{r}
}

// PlateauDatasetType returns PlateauDatasetTypeResolver implementation.
func (r *Resolver) PlateauDatasetType() PlateauDatasetTypeResolver {
	return &plateauDatasetTypeResolver{r}
}

// PlateauSpec returns PlateauSpecResolver implementation.
func (r *Resolver) PlateauSpec() PlateauSpecResolver { return &plateauSpecResolver{r} }

// PlateauSpecMinor returns PlateauSpecMinorResolver implementation.
func (r *Resolver) PlateauSpecMinor() PlateauSpecMinorResolver { return &plateauSpecMinorResolver{r} }

// Prefecture returns PrefectureResolver implementation.
func (r *Resolver) Prefecture() PrefectureResolver { return &prefectureResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// RelatedDataset returns RelatedDatasetResolver implementation.
func (r *Resolver) RelatedDataset() RelatedDatasetResolver { return &relatedDatasetResolver{r} }

// RelatedDatasetItem returns RelatedDatasetItemResolver implementation.
func (r *Resolver) RelatedDatasetItem() RelatedDatasetItemResolver {
	return &relatedDatasetItemResolver{r}
}

// RelatedDatasetType returns RelatedDatasetTypeResolver implementation.
func (r *Resolver) RelatedDatasetType() RelatedDatasetTypeResolver {
	return &relatedDatasetTypeResolver{r}
}

// Ward returns WardResolver implementation.
func (r *Resolver) Ward() WardResolver { return &wardResolver{r} }

type cityResolver struct{ *Resolver }
type cityGMLDatasetResolver struct{ *Resolver }
type genericDatasetResolver struct{ *Resolver }
type genericDatasetItemResolver struct{ *Resolver }
type genericDatasetTypeResolver struct{ *Resolver }
type plateauDatasetResolver struct{ *Resolver }
type plateauDatasetItemResolver struct{ *Resolver }
type plateauDatasetTypeResolver struct{ *Resolver }
type plateauSpecResolver struct{ *Resolver }
type plateauSpecMinorResolver struct{ *Resolver }
type prefectureResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type relatedDatasetResolver struct{ *Resolver }
type relatedDatasetItemResolver struct{ *Resolver }
type relatedDatasetTypeResolver struct{ *Resolver }
type wardResolver struct{ *Resolver }
