name: ci-worker
on:
  push:
    branches: [main, release]
    paths:
      - worker/**
      - .github/workflows/ci_worker.yml
      - .github/workflows/deploy_test.yml
      - .github/workflows/pr_title.yml
      - .github/workflows/stage.yml
      - .github/workflows/release.yml
      - .github/workflows/decompressor_build.yml
      - .github/workflows/worker_build.yml
  pull_request:
    paths:
      - worker/**
      - .github/workflows/ci_worker.yml
      - .github/workflows/deploy_test.yml
      - .github/workflows/pr_title.yml
      - .github/workflows/stage.yml
      - .github/workflows/release.yml
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worker
    services:
      mongo:
        image: mongo:6-focal
        ports:
          - 27017:27017
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          working-directory: worker
          args: --config=../.golangci.yml
      - name: test
        run: go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic
        env:
          REEARTH_CMS_WORKER_DB: mongodb://localhost
      - name: codecov
        uses: codecov/codecov-action@v4
        with:
          flags: worker
          file: coverage.txt
