export enum PlateauDatasetType {
  Border = "border",
  Bridge = "brid",
  Building = "bldg",
  CityFurniture = "frn",
  EmergencyRoute = "emergency_route",
  Global = "global",
  GenericCityObject = "gen",
  HighTideRisk = "htd",
  InlandFloodingRisk = "ifld",
  LandSlideRisk = "lsld",
  LandUse = "luse",
  Landmark = "landmark",
  Park = "park",
  Railway = "railway",
  RiverFloodingRisk = "fld",
  Road = "tran",
  Shelter = "shelter",
  Station = "station",
  TsunamiRisk = "tnm",
  UrbanPlanning = "urf",
  UseCase = "usecase",
  Vegetation = "veg",
  Sample = "sample",
  Constructure = "cons",
  Water = "wtr",
  Traffic = "trk",
}
