import { PlateauDatasetType } from "./plateau";

export const datasetTypeOrder = [
  PlateauDatasetType.Building,
  PlateauDatasetType.Bridge,
  PlateauDatasetType.Border,
  PlateauDatasetType.Landmark,
  PlateauDatasetType.Station,
  PlateauDatasetType.Road,
  PlateauDatasetType.Railway,
  PlateauDatasetType.Park,
  PlateauDatasetType.LandUse,
  PlateauDatasetType.RiverFloodingRisk,
  PlateauDatasetType.InlandFloodingRisk,
  PlateauDatasetType.HighTideRisk,
  PlateauDatasetType.LandSlideRisk,
  PlateauDatasetType.TsunamiRisk,
  PlateauDatasetType.Shelter,
  PlateauDatasetType.EmergencyRoute,
  PlateauDatasetType.UrbanPlanning,
  PlateauDatasetType.CityFurniture,
  PlateauDatasetType.Vegetation,
  PlateauDatasetType.UseCase,
  PlateauDatasetType.GenericCityObject,
];
