export const FIELD_CATEGORY_GENERAL = "General";
export const FIELD_CATEGORY_POINT = "Point";
export const FIELD_CATEGORY_POLYLINE = "Polyline";
export const FIELD_CATEGORY_POLYGON = "Polygon";
export const FIELD_CATEGORY_THREE_D_TILES = "3d tiles";

export const FILED_GROUP_GENERAL_TIMELINE = "FILED_GROUP_GENERAL_TIMELINE";

export const FIELD_GROUP_POINT_FILL_COLOR = "FIELD_GROUP_POINT_FILL_COLOR";
export const FIELD_GROUP_POINT_VISIBILITY = "FIELD_GROUP_POINT_VISIBILITY";
export const FIELD_GROUP_POINT_USE_IMAGE = "FIELD_GROUP_POINT_USE_IMAGE";

export const FIELD_GROUP_POLYLINE_FILL_COLOR = "FIELD_GROUP_POLYLINE_FILL_COLOR";
export const FIELD_GROUP_POLYLINE_VISIBILITY = "FIELD_GROUP_POLYLINE_VISIBILITY";

export const FIELD_GROUP_POLYGON_FILL_COLOR = "FIELD_GROUP_POLYGON_FILL_COLOR";
export const FIELD_GROUP_POLYGON_VISIBILITY = "FIELD_GROUP_POLYGON_VISIBILITY";

export const FIELD_GROUP_THREE_D_TILES_FILL_COLOR = "FIELD_GROUP_THREE_D_TILES_FILL_COLOR";
export const FIELD_GROUP_THREE_D_TILES_FILTER = "FIELD_GROUP_THREE_D_TILES_FILTER";
export const FIELD_GROUP_THREE_D_TILES_CLIPPING = "FIELD_GROUP_THREE_D_TILES_CLIPPING";

export type FieldGroupTypes =
  | typeof FIELD_GROUP_POINT_FILL_COLOR
  | typeof FIELD_GROUP_POINT_VISIBILITY
  | typeof FIELD_GROUP_POINT_USE_IMAGE
  | typeof FIELD_GROUP_POLYLINE_FILL_COLOR
  | typeof FIELD_GROUP_POLYLINE_VISIBILITY
  | typeof FIELD_GROUP_POLYGON_FILL_COLOR
  | typeof FIELD_GROUP_POLYGON_VISIBILITY
  | typeof FIELD_GROUP_THREE_D_TILES_FILL_COLOR
  | typeof FIELD_GROUP_THREE_D_TILES_FILTER
  | typeof FIELD_GROUP_THREE_D_TILES_CLIPPING
  | typeof FILED_GROUP_GENERAL_TIMELINE;

export const fieldGroupTitles = {
  FIELD_GROUP_POINT_FILL_COLOR: "Fill Color",
  FIELD_GROUP_POINT_VISIBILITY: "Visibility",
  FIELD_GROUP_POINT_USE_IMAGE: "Use Image",
  FIELD_GROUP_POLYLINE_FILL_COLOR: "Fill Color",
  FIELD_GROUP_POLYLINE_VISIBILITY: "Visibility",
  FIELD_GROUP_POLYGON_FILL_COLOR: "Color",
  FIELD_GROUP_POLYGON_VISIBILITY: "Visibility",
  FIELD_GROUP_THREE_D_TILES_FILL_COLOR: "Color",
  FIELD_GROUP_THREE_D_TILES_FILTER: "Filter",
  FIELD_GROUP_THREE_D_TILES_CLIPPING: "Clipping",
  FILED_GROUP_GENERAL_TIMELINE: "Timeline",
};
