name: ci-server
on:
  workflow_call:
env:
  GO_VERSION: '1.21'
jobs:
  ci-server-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: server
          args: --timeout=5m
  ci-server-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: server/go.sum
      - name: test
        working-directory: server
        run: go test ./... -v -race -tags draco
