name: ci-worker
on:
  workflow_call:
env:
  GO_VERSION: "1.21"
jobs:
  ci-worker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: worker
          args: --timeout=5m
  ci-worker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: worker/go.sum
      - name: test
        working-directory: worker
        run: go test ./... -v -race
