name: ⭐️ Deploy PLATEAU Geo dev
on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-geo-dev]
env:
  IMAGE: ghcr.io/eukarya-inc/plateau-view-3.0/plateauview-geo:latest
  IMAGE_GCP: asia.gcr.io/reearth-plateau-dev/plateauview-geo:latest
jobs:
  deploy_geo:
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'eukarya-inc/PLATEAU-VIEW-3.0'
    environment: dev
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Configure docker
        run: gcloud auth configure-docker --quiet
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download geo artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml
          workflow_conclusion: success
          branch: main
          name: plateauview-geo
          check_artifacts: true
      - name: Unpack docker image
        run: docker load < plateauview-geo.tar.gz
      - name: docker push
        run: |
          docker tag $IMAGE $IMAGE_GCP && \
          docker push $IMAGE &&
          docker push $IMAGE_GCP
      - name: Deploy geo to Cloud Run
        run: |
          gcloud run deploy plateauview-geo \
            --image $IMAGE_GCP \
            --region $GCP_REGION \
            --platform managed \
            --quiet
        env:
          GCP_REGION: ${{ vars.GCP_REGION }}
